# -*- coding: utf-8 -*-
"""heart_disease_research2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WnrHF8mhSjNdPGSoEicCKynz6lCvEZTG
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from scipy import stats

"""# **ABOUT DATASET**

This dataset contains 10,000 observations and 20 health-related features describing
demographic variables (e.g., Age, Gender), lifestyle factors (e.g., Smoking, Exercise Habits),
clinical indicators (e.g., Blood Pressure, Cholesterol Level, BMI), and inflammatory markers
(e.g., CRP Level, Homocysteine Level). The target variable is Heart Disease Status (Yes/No).

# **DESCRIPTIVE STATISTICS & VISUAL DATA ANALYSIS**

# **1. Load dataset and show the first few rows of the dataset**
"""

# Load dataset
path = "heart_disease.csv"
df = pd.read_csv(path)

print("Shape:", df.shape)
print("Columns:", list(df.columns))
print("\nDtypes:\n", df.dtypes)

# Create a binary target (0/1) for numeric comparisons
# Heart Disease Status: Yes/No
df["target"] = df["Heart Disease Status"].map({"No": 0, "Yes": 1})

# Preview
display(df.head())

"""# **2. Data Quality Checks (Missing Values, Duplicates)**"""

# Missing values
missing = df.isna().sum().sort_values(ascending=False)
missing_pct = (missing / len(df) * 100).round(2)

missing_table = pd.DataFrame({
    "missing_count": missing,
    "missing_percent": missing_pct
})
display(missing_table)

# Duplicates
dup_count = df.duplicated().sum()
print("Duplicate rows:", dup_count)

# Target sanity check
print("\nTarget distribution (raw):")
display(df["Heart Disease Status"].value_counts())

print("\nTarget distribution (binary):")
display(df["target"].value_counts())

"""There are no duplicate rows, but missing values exist across multiple columns, with Alcohol Consumption being the most incomplete feature.

# **3. Target Distribution (Class balance)**
"""

counts = df["Heart Disease Status"].value_counts()
rate = df["target"].mean()

print("Heart disease prevalence (Yes=1):", round(rate, 3))
display(counts)

# Simple bar chart
plt.figure()
counts.plot(kind="bar")
plt.title("Target Distribution: Heart Disease Status")
plt.xlabel("Class")
plt.ylabel("Count")
plt.show()

"""The dataset is imbalanced (~80% No vs ~20% Yes), so comparisons should focus on effect sizes and practical differences, not only p-values.

# **4. Univariate Analysis (Numeric feature distributions)**
"""

# Numeric columns (excluding binary target)
num_cols = df.select_dtypes(include=[np.number]).columns.tolist()
num_cols = [c for c in num_cols if c != "target"]

# Descriptive statistics using available values only
desc_stats = df[num_cols].describe().T
display(desc_stats)

# Histograms (drop missing values per feature)
for col in num_cols:
    plt.figure()
    df[col].dropna().hist(bins=30)
    plt.title(f"Distribution of {col}")
    plt.xlabel(col)
    plt.ylabel("Count")
    plt.show()

"""Numeric feature distributions appear broadly plausible; however, interpretation should account for missing values and potential synthetic/normalized patterns in biomarkers.

# **5. Univariate Analysis (Categorical feature distributions)**
"""

cat_cols = df.select_dtypes(include=["object"]).columns.tolist()
cat_cols = [c for c in cat_cols if c != "Heart Disease Status"]

for col in cat_cols:
    print(f"\nValue counts for: {col}")
    display(df[col].value_counts(dropna=False))

"""Categorical variables have clear, interpretable categories (e.g., High/Medium/Low), making them suitable for prevalence and risk-rate comparisons.

# **6. Bivariate Analysis vs Target (Numeric)**
"""

# Grouped stats
group_stats = df.groupby("target")[num_cols].agg(["mean", "median", "std"]).round(3)
display(group_stats)

# Cohen's d
def cohens_d(a, b):
    a = np.asarray(a); b = np.asarray(b)
    n1, n2 = len(a), len(b)
    s1, s2 = a.var(ddof=1), b.var(ddof=1)
    pooled = ((n1-1)*s1 + (n2-1)*s2) / (n1 + n2 - 2)
    return (a.mean() - b.mean()) / np.sqrt(pooled)

# Welch's t-test + effect sizes
rows = []
for col in num_cols:
    a = df[df["target"] == 0][col].dropna()
    b = df[df["target"] == 1][col].dropna()
    t_stat, p_val = stats.ttest_ind(a, b, equal_var=False)
    rows.append({
        "feature": col,
        "mean_no_disease": a.mean(),
        "mean_disease": b.mean(),
        "t_stat": t_stat,
        "p_value": p_val,
        "cohens_d": cohens_d(a, b)
    })

num_tests = pd.DataFrame(rows).sort_values("p_value")
display(num_tests)

# Boxplots
for col in num_cols:
    plt.figure()
    df.boxplot(column=col, by="target")
    plt.title(f"{col} by Heart Disease Status")
    plt.suptitle("")
    plt.xlabel("target (0=No, 1=Yes)")
    plt.ylabel(col)
    plt.show()

"""**Goal**

Compare numeric features between No Disease (0) and Disease (1) groups:

```
group means/medians

Welch’s t-test

Cohen’s d (effect size)

boxplots for interpretability
```



**Conclusion**

In this dataset, numeric differences between groups tend to be small (effect sizes close to zero). If p-values become significant, it may be driven by large sample size rather than strong clinical separation.

# **7. Bivariate Analysis vs Target (Categorical)**
"""

cat_features = df.select_dtypes(include=["object"]).columns.tolist()
cat_features = [c for c in cat_features if c != "Heart Disease Status"]

def category_disease_rate(data, col, target="target"):
    tmp = data[[col, target]].dropna()
    rate = tmp.groupby(col)[target].mean().sort_values(ascending=False)
    count = tmp[col].value_counts()
    out = pd.DataFrame({"count": count, "disease_rate": rate})
    return out.sort_values("disease_rate", ascending=False)

# Disease rates per category
for col in cat_features:
    print(f"\nDisease rate by category: {col}")
    display(category_disease_rate(df, col))

# Chi-square association tests
chi_rows = []
for col in cat_features:
    tmp = df[[col, "target"]].dropna()
    table = pd.crosstab(tmp[col], tmp["target"])
    chi2, p, dof, expected = stats.chi2_contingency(table)
    chi_rows.append({"feature": col, "chi2": chi2, "p_value": p, "dof": dof})

chi_df = pd.DataFrame(chi_rows).sort_values("p_value")
display(chi_df)

"""**Goal**

For each categorical feature:

```
disease rate per category

chi-square test for association
```



**Conclusion**

Some categorical features may show statistically detectable differences, but practical differences may still be modest. Report both disease rates and p-values.

# **8. Correlation & Relationships**
"""

corr_cols = num_cols + ["target"]
corr = df[corr_cols].corr()
display(corr)

# Correlation heatmap (matplotlib)
plt.figure()
plt.imshow(corr, aspect="auto")
plt.xticks(range(len(corr_cols)), corr_cols, rotation=45, ha="right")
plt.yticks(range(len(corr_cols)), corr_cols)
plt.title("Correlation Matrix (Numeric Features + Target)")
plt.colorbar()
plt.tight_layout()
plt.show()

# Correlation with target only (more readable for website/report)
corr_with_target = corr["target"].drop("target").sort_values()

plt.figure()
corr_with_target.plot(kind="barh")
plt.title("Correlation with Heart Disease (Target)")
plt.xlabel("Correlation")
plt.show()

"""Correlations with the target may be weak; this supports the earlier conclusion that single variables do not strongly separate the classes in this dataset.

# **9. Findings Summary Generator**

1) The dataset contains 10,000 observations and a wide range of demographic, lifestyle, and biomarker-related features, making it useful for exploratory cardiovascular analysis.

2) Heart disease prevalence is approximately 20%, meaning the dataset is class-imbalanced. Interpretations should focus on practical significance (effect sizes) rather than only statistical significance.

3) Several variables show only small differences between disease and no-disease groups. This suggests that in this dataset, cardiovascular risk patterns may be multi-factorial and not strongly separable using single features alone.

4) Missing data is a key limitation—especially in Alcohol Consumption—and must be handled carefully to avoid biased comparisons.

5) The selected website visualizations provide an interpretable summary of prevalence, lifestyle-related disease rates, feature effect sizes, and data quality.

# **10. Graphics for the website**

**10.1 Target Prevalence**

Heart disease is present in approximately 20% of patients in this dataset. This imbalance is important for interpretation: even if some associations are statistically significant, practical effect sizes may remain small.
"""

counts = df["Heart Disease Status"].value_counts()

plt.figure()
counts.plot(kind="bar")
plt.title("Heart Disease Prevalence")
plt.xlabel("Class")
plt.ylabel("Number of Patients")
plt.show()

"""**10.2 Heart Disease Rate by Stress Level**

Stress level shows visible differences in disease prevalence across categories. This suggests that stress-related lifestyle context may contribute to cardiovascular risk patterns in the dataset.
"""

rates = df.dropna(subset=["Stress Level"]).groupby("Stress Level")["target"].mean().sort_values()

plt.figure()
rates.plot(kind="bar")
plt.title("Heart Disease Rate by Stress Level")
plt.xlabel("Stress Level")
plt.ylabel("Disease Rate (Yes=1)")
plt.ylim(0, 1)
plt.show()

"""**10.3 BMI Distribution by Disease Status**

BMI distributions between groups are very close, indicating that BMI alone provides limited separation between healthy and diseased patients in this dataset. This supports the idea that cardiovascular disease risk is multi-factorial.
"""

feature = "BMI"

plt.figure()
df[df["target"] == 0][feature].dropna().hist(alpha=0.6, bins=30, label="No Heart Disease")
df[df["target"] == 1][feature].dropna().hist(alpha=0.6, bins=30, label="Heart Disease")
plt.title("BMI Distribution by Heart Disease Status")
plt.xlabel("BMI")
plt.ylabel("Count")
plt.legend()
plt.show()

"""**10.4 Effect Size Ranking (Numeric Features)**

This chart ranks numeric features by effect size (Cohen’s d). Features closer to zero indicate minimal difference between groups. This helps distinguish statistically significant results from practically meaningful ones.
"""

# Recompute effect sizes (standalone)
def cohens_d(a, b):
    a = np.asarray(a); b = np.asarray(b)
    n1, n2 = len(a), len(b)
    s1, s2 = a.var(ddof=1), b.var(ddof=1)
    pooled = ((n1-1)*s1 + (n2-1)*s2) / (n1 + n2 - 2)
    return (a.mean() - b.mean()) / np.sqrt(pooled)

effect_rows = []
for col in num_cols:
    a = df[df["target"] == 0][col].dropna()
    b = df[df["target"] == 1][col].dropna()
    effect_rows.append({"feature": col, "cohens_d": cohens_d(a, b)})

effect_df = pd.DataFrame(effect_rows).sort_values("cohens_d")

plt.figure()
effect_df.plot(x="feature", y="cohens_d", kind="barh", legend=False)
plt.axvline(0, linestyle="--")
plt.title("Effect Size of Numeric Features (Cohen's d)")
plt.xlabel("Cohen's d")
plt.ylabel("Feature")
plt.show()

"""**10.5 Missing Data Overview (Data Quality)**

Some features contain missing values (especially Alcohol Consumption). This matters because missingness can bias category comparisons unless handled explicitly (e.g., dropping missing rows per feature or treating missing as “Unknown”).
"""

missing = df.isna().sum().sort_values(ascending=False)
missing = missing[missing > 0]

plt.figure()
missing.plot(kind="bar")
plt.title("Missing Values per Feature")
plt.xlabel("Feature")
plt.ylabel("Missing Count")
plt.show()