# -*- coding: utf-8 -*-
"""heart_disease_uci.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_cl0Nq0X2drrn6Esprw4-jaOzT1m7Qjd
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from scipy import stats

"""# **ABOUT DATASET**
**Context**

This is a multivariate type of dataset which means providing or involving a variety of separate mathematical or statistical variables, multivariate numerical data analysis. It is composed of 14 attributes which are age, sex, chest pain type, resting blood pressure, serum cholesterol, fasting blood sugar, resting electrocardiographic results, maximum heart rate achieved, exercise-induced angina, oldpeak — ST depression induced by exercise relative to rest, the slope of the peak exercise ST segment, number of major vessels and Thalassemia. This database includes 76 attributes, but all published studies relate to the use of a subset of 14 of them. The Cleveland database is the only one used by ML researchers to date. One of the major tasks on this dataset is to predict based on the given attributes of a patient that whether that particular person has heart disease or not and other is the experimental task to diagnose and find out various insights from this dataset which could help in understanding the problem more.

**Content**

*Column Descriptions*:

*  `id` (Unique id for each patient)
*  `age` (Age of the patient in years)
origin (place of study)
*  `sex` (Male/Female)
*  `cp chest pain type` ([typical angina, atypical angina, non-anginal, asymptomatic])
*  `trestbps resting blood pressure` (resting blood pressure (in mm Hg on admission to the hospital))
*  `chol` (serum cholesterol in mg/dl)
*  `fbs` (if fasting blood sugar > 120 mg/dl)
*  `restecg` (resting electrocardiographic results)
-- Values: [normal, stt abnormality, lv hypertrophy]
*  `thalach` (maximum heart rate achieved)
*  `exang` (exercise-induced angina (True/ False))
*  `oldpeak` (ST depression induced by exercise relative to rest)
*  `slope` (the slope of the peak exercise ST segment)
*  `ca` (number of major vessels (0-3) colored by fluoroscopy)
*  `thal` [normal; fixed defect; reversible defect]
*  `num` (the predicted attribute)

**Acknowledgements**

*Creators*:

*  Hungarian Institute of Cardiology. Budapest: Andras Janosi, M.D.
*  University Hospital, Zurich, Switzerland: William Steinbrunn, M.D.
*  University Hospital, Basel, Switzerland: Matthias Pfisterer, M.D.
*  V.A. Medical Center, Long Beach and Cleveland Clinic Foundation: Robert Detrano, M.D., Ph.D.

*Relevant Papers*:

*  Detrano, R., Janosi, A., Steinbrunn, W., Pfisterer, M., Schmid, J., Sandhu, S., Guppy, K., Lee, S., & Froelicher, V. (1989). International application of a new probability algorithm for the diagnosis of coronary artery disease.
*  American Journal of Cardiology, 64,304--310.

*Web Link*:
*  David W. Aha & Dennis Kibler. "Instance-based prediction of heart-disease presence with the Cleveland database." Web Link
*  Gennari, J.H., Langley, P, & Fisher, D. (1989). Models of incremental concept formation. Artificial Intelligence, 40, 11--61. Web Link

`Citation Request:`

The authors of the databases have requested that any publications resulting from the use of the data include the names of the principal investigator responsible for the data collection at each institution. They would be:

Hungarian Institute of Cardiology. Budapest: Andras Janosi,

*   M.D.: University Hospital, Zurich, Switzerland: William Steinbrunn, M.D.
*   University Hospital, Basel, Switzerland: Matthias Pfisterer, M.D.
*   V.A. Medical Center, Long Beach and Cleveland Clinic Foundation:Robert Detrano, M.D., Ph.D.

# **DESCRIPTIVE STATISTICS & VISUAL DATA ANALYSIS**

# **1. Load dataset and show the first few rows of the dataset**
"""

# Load dataset
path = "heart_disease_uci.csv"
df = pd.read_csv(path)

print("Shape:", df.shape)
print("Columns:", list(df.columns))
print("\nData types:")
display(df.dtypes)

display(df.head())

"""# **2. Data Quality Checks (Missing Values, Duplicates)**"""

# Missing values
missing = df.isna().sum().sort_values(ascending=False)
missing_pct = (missing / len(df) * 100).round(2)

missing_table = pd.DataFrame({
    "missing_count": missing,
    "missing_percent": missing_pct
})
display(missing_table)

# Duplicate check
print("Duplicate rows:", df.duplicated().sum())

"""Missing values are present but limited. A feature-specific handling strategy (dropping missing values per analysis) is appropriate and avoids unnecessary data loss.

# **3. Target Distribution (Class balance)**

(In UCI datasets, the target is often target or num.
If num exists, heart disease is defined as num > 0.)

The target variable is converted into a binary indicator of heart disease presence.
"""

# Define target (adjust if needed)
if "num" in df.columns:
    df["target"] = (df["num"] > 0).astype(int)
elif "target" in df.columns:
    df["target"] = df["target"].astype(int)

target_counts = df["target"].value_counts()
target_rate = df["target"].mean()

display(target_counts)
print("Heart disease prevalence:", round(target_rate, 3))

plt.figure()
target_counts.plot(kind="bar")
plt.title("Target Distribution: Heart Disease (UCI)")
plt.xlabel("Class (0 = No Disease, 1 = Disease)")
plt.ylabel("Count")
plt.show()

"""The dataset contains both healthy individuals and patients with heart disease, enabling meaningful group comparisons.

# **4. Univariate Analysis (Numeric feature distributions)**
"""

num_cols = df.select_dtypes(include=[np.number]).columns.tolist()
num_cols = [c for c in num_cols if c not in ["target", "num"]]

display(df[num_cols].describe().T)

for col in num_cols:
    plt.figure()
    df[col].dropna().hist(bins=30)
    plt.title(f"Distribution of {col}")
    plt.xlabel(col)
    plt.ylabel("Count")
    plt.show()

"""Numeric features show clinically plausible distributions, with noticeable variability in age, cholesterol levels, and exercise-related measurements.

# **5. Univariate Analysis (Categorical feature distributions)**
"""

cat_cols = df.select_dtypes(include=["object"]).columns.tolist()

for col in cat_cols:
    print(f"\nValue counts for: {col}")
    display(df[col].value_counts(dropna=False))

"""Certain categorical variables show uneven distributions, suggesting potential associations with heart disease risk.

# **6. Bivariate Analysis vs Target (Numeric)**
"""

def cohens_d(a, b):
    a = np.asarray(a); b = np.asarray(b)
    n1, n2 = len(a), len(b)
    s1, s2 = a.var(ddof=1), b.var(ddof=1)
    pooled = ((n1-1)*s1 + (n2-1)*s2) / (n1 + n2 - 2)
    return (a.mean() - b.mean()) / np.sqrt(pooled)

rows = []

for col in num_cols:
    a = df[df["target"] == 0][col].dropna()
    b = df[df["target"] == 1][col].dropna()

    if len(a) < 30 or len(b) < 30:
        continue

    t_stat, p_val = stats.ttest_ind(a, b, equal_var=False)

    rows.append({
        "feature": col,
        "mean_no_disease": a.mean(),
        "mean_disease": b.mean(),
        "p_value": p_val,
        "cohens_d": cohens_d(a, b)
    })

num_results = pd.DataFrame(rows).sort_values("p_value")
display(num_results)

"""Several numeric variables differ between groups, but effect sizes indicate that no single numeric feature provides strong standalone discrimination.

# **7. Bivariate Analysis vs Target (Categorical)**
"""

def category_disease_rate(df, col):
    tmp = df[[col, "target"]].dropna()
    rate = tmp.groupby(col)["target"].mean().sort_values(ascending=False)
    count = tmp[col].value_counts()
    return pd.DataFrame({"count": count, "disease_rate": rate})

chi_rows = []

for col in cat_cols:
    display(category_disease_rate(df, col))

    table = pd.crosstab(df[col], df["target"])
    chi2, p, dof, _ = stats.chi2_contingency(table)
    chi_rows.append({"feature": col, "chi2": chi2, "p_value": p})

chi_df = pd.DataFrame(chi_rows).sort_values("p_value")
display(chi_df)

"""Categorical features related to chest pain and ECG findings show stronger associations with heart disease than most numeric features.

# **8. Correlation & Relationships**
"""

corr_cols = num_cols + ["target"]
corr_matrix = df[corr_cols].corr()

display(corr_matrix)

plt.figure(figsize=(10, 8))
plt.imshow(corr_matrix, aspect="auto")
plt.xticks(range(len(corr_cols)), corr_cols, rotation=45, ha="right")
plt.yticks(range(len(corr_cols)), corr_cols)
plt.colorbar(label="Correlation coefficient")
plt.title("Correlation Matrix: UCI Heart Disease Dataset")
plt.tight_layout()
plt.show()

corr_with_target = corr_matrix["target"].drop("target").sort_values()

plt.figure()
corr_with_target.plot(kind="barh")
plt.title("Correlation with Heart Disease (UCI Dataset)")
plt.xlabel("Correlation coefficient")
plt.show()

"""Exercise-related and ECG-related variables tend to show stronger correlations with heart disease than laboratory measurements.

# **9. Findings Summary Generator**

1) The UCI Heart Disease dataset contains clinically meaningful features widely used in cardiovascular diagnosis.

2) Heart disease prevalence is substantial, enabling reliable comparison between healthy and diseased individuals.

3) Numeric features alone provide limited discrimination, with generally small to moderate effect sizes.

4) Categorical and exercise-related variables (e.g., chest pain type, maximum heart rate) show stronger associations with heart disease.

5) Overall, the dataset supports the conclusion that heart disease risk is multi-factorial, requiring integrated consideration of demographic, clinical, and functional indicators.

# **10. Graphics for the website**

**10.1 Heart Disease Rate by Chest Pain Type**
"""

feature = "cp" if "cp" in df.columns else "chest_pain"

rates = df.groupby(feature)["target"].mean()

plt.figure()
rates.plot(kind="bar")
plt.title("Heart Disease Rate by Chest Pain Type")
plt.ylabel("Disease Rate")
plt.ylim(0, 1)
plt.show()

"""Asymptomatic and atypical chest pain categories exhibit higher heart disease prevalence, highlighting the diagnostic importance of chest pain classification.

**10.2 Maximum Heart Rate by Disease Status**
"""

feature = "thalach" if "thalach" in df.columns else "max_heart_rate"

plt.figure()
df[df["target"] == 0][feature].dropna().hist(alpha=0.6, bins=30, label="No Disease")
df[df["target"] == 1][feature].dropna().hist(alpha=0.6, bins=30, label="Disease")
plt.legend()
plt.title("Maximum Heart Rate Distribution by Disease Status")
plt.xlabel(feature)
plt.ylabel("Count")
plt.show()

"""Patients with heart disease tend to achieve lower maximum heart rates during exercise testing.

**10.3 Effect Size Ranking (Numeric Features)**
"""

effect_df = num_results[["feature", "cohens_d"]].sort_values("cohens_d")

plt.figure()
effect_df.plot(x="feature", y="cohens_d", kind="barh", legend=False)
plt.axvline(0, linestyle="--")
plt.title("Effect Size of Numeric Features (Cohen’s d)")
plt.xlabel("Cohen’s d")
plt.show()

"""Effect size ranking highlights exercise-related features as the most discriminative, although effect sizes remain moderate."""