# -*- coding: utf-8 -*-
"""heart_statlog_cleveland_hungary_final.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/139hZHDxAnGv8CS3GV-HY6hkr-P7dzg8B
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from scipy import stats

"""# **ABOUT DATASET**

This heart disease dataset is curated by combining 5 popular heart disease datasets already available independently but not combined before. In this dataset, 5 heart datasets are combined over 11 common features which makes it the largest heart disease dataset available so far for research purposes. The five datasets used for its curation are:

Cleveland
Hungarian
Switzerland
Long Beach VA
Statlog (Heart) Data Set.
This dataset consists of 1190 instances with 11 features. These datasets were collected and combined at one place to help advance research on CAD-related machine learning and data mining algorithms, and hopefully to ultimately advance clinical diagnosis and early treatment.

# **DESCRIPTIVE STATISTICS & VISUAL DATA ANALYSIS**

# **1. Load dataset and show the first few rows of the dataset**
"""

# 1) Load dataset
path = "heart_statlog_cleveland_hungary_final.csv"
df = pd.read_csv(path)

# 2) Quick overview
print("Shape (rows, cols):", df.shape)
display(df.head(10))

# 3) Column names
print("Columns:", list(df.columns))

# 4) Data types
display(df.dtypes)

"""The dataset contains 1,190 observations and 11 clinical features, confirming that it is sufficiently large and structured for meaningful exploratory data analysis.

# **2. Feature Dictionary (Human-readable meaning)**
"""

# Feature dictionary based on documentation
feature_info = {
    "age": "Age in years (numeric)",
    "sex": "Sex (1=male, 0=female)",
    "chest pain type": "Chest pain type (1=typical angina, 2=atypical angina, 3=non-anginal pain, 4=asymptomatic)",
    "resting bp s": "Resting blood pressure in mm Hg (numeric)",
    "cholesterol": "Serum cholesterol in mg/dl (numeric)",
    "fasting blood sugar": "Fasting blood sugar >120 mg/dl (1=true, 0=false)",
    "resting ecg": "Resting ECG (0=normal, 1=ST-T abnormality, 2=LV hypertrophy)",
    "max heart rate": "Maximum heart rate achieved (numeric)",
    "exercise angina": "Exercise-induced angina (1=yes, 0=no)",
    "oldpeak": "ST depression induced by exercise relative to rest (numeric)",
    "ST slope": "Slope of peak exercise ST segment (commonly 1=up, 2=flat, 3=down; sometimes includes 0)",
    "target": "Class label (1=heart disease, 0=normal)",
}

# Print in a readable way
for k, v in feature_info.items():
    print(f"- {k}: {v}")

"""# **3. Data Quality Checks (Missing values, duplicates, validity)**"""

# 1) Missing values
missing = df.isna().sum().sort_values(ascending=False)
print("Missing values per column:")
display(missing)

# 2) Duplicate rows
dup_count = df.duplicated().sum()
print("Duplicate rows:", dup_count)

# 3) Quick sanity checks for expected value ranges/categories
cat_cols = ["sex", "chest pain type", "fasting blood sugar", "resting ecg", "exercise angina", "ST slope", "target"]
for col in cat_cols:
    print(col, "unique:", sorted(df[col].unique()))

# Drop duplicates
df = df.drop_duplicates().reset_index(drop=True)

"""After removing duplicate entries, the dataset shows no critical data quality issues, indicating that it is suitable for downstream statistical analysis without extensive preprocessing.

# **4. Target Distribution (Class balance)**
"""

# Target counts and rate
target_counts = df["target"].value_counts()
target_rate = df["target"].mean()

print("Target counts:")
display(target_counts)

print(f"Heart disease prevalence (target=1): {target_rate:.3f}")

"""Heart disease cases represent a substantial portion of the dataset, enabling reliable comparison between healthy individuals and patients with cardiovascular disease.

# **5. Univariate Analysis (Numeric feature distributions)**
"""

num_cols = ["age", "resting bp s", "cholesterol", "max heart rate", "oldpeak"]

# Summary statistics
display(df[num_cols].describe().T)

# Histograms (one by one, clean and readable)
for col in num_cols:
    plt.figure()
    df[col].hist(bins=30)
    plt.title(f"Distribution of {col}")
    plt.xlabel(col)
    plt.ylabel("Count")
    plt.show()

"""Numeric features show diverse distributions, with exercise-related variables displaying greater variability, suggesting their potential importance in differentiating cardiovascular risk.

Certain categories, particularly asymptomatic chest pain and exercise-induced angina, appear frequently among patients with heart disease, warranting deeper investigation.

# **6. Univariate Analysis (Categorical feature distributions)**
"""

cat_cols = ["sex", "chest pain type", "fasting blood sugar", "resting ecg", "exercise angina", "ST slope"]

for col in cat_cols:
    print(f"\nValue counts for: {col}")
    display(df[col].value_counts().sort_index())

"""# **7. Bivariate Analysis vs Target (Numeric)**

7.1 Grouped stats (mean/median/std by target)
"""

group_stats = df.groupby("target")[num_cols].agg(["mean", "median", "std"]).round(2)
display(group_stats)

"""7.2 Quick significance check (t-test; descriptive, not ML)"""

# Welch's t-test (doesn't assume equal variance)
test_rows = []
for col in num_cols:
    a = df[df["target"] == 0][col]
    b = df[df["target"] == 1][col]
    t, p = stats.ttest_ind(a, b, equal_var=False)
    test_rows.append({
        "feature": col,
        "mean_target0": a.mean(),
        "mean_target1": b.mean(),
        "t_stat": t,
        "p_value": p
    })

ttest_df = pd.DataFrame(test_rows).sort_values("p_value")
display(ttest_df)

"""7.3 Boxplots (numeric vs target)"""

for col in num_cols:
    plt.figure()
    df.boxplot(column=col, by="target")
    plt.title(f"{col} by target")
    plt.suptitle("")  # removes automatic title
    plt.xlabel("target (0=normal, 1=disease)")
    plt.ylabel(col)
    plt.show()

"""### Summary of Numeric Bivariate Analysis

The bivariate analysis of numeric features against the target variable (`target`) reveals several statistically significant differences between individuals with and without heart disease. The Welch's t-test, which does not assume equal variances, was used to assess these differences, and box plots provided visual confirmation of the distributions.

- **Oldpeak**: This feature shows a highly significant difference (p = 1.90e-40). Individuals with heart disease (`target=1`) exhibit a significantly **higher** mean `oldpeak` (1.57) compared to those without heart disease (`target=0`) (0.42). This suggests greater ST depression during exercise in the disease group.

- **Max Heart Rate**: A strong significant difference is observed (p = 1.43e-36). The mean `max heart rate` is significantly **lower** in the heart disease group (130.68) than in the no disease group (160.01), indicating a reduced maximum cardiac effort capacity in diseased individuals.

- **Age**: Age is also significantly different between the groups (p = 6.35e-18). The heart disease group has a significantly **higher** mean `age` (57.19 years) compared to the no disease group (51.68 years), suggesting that age is a risk factor.

- **Cholesterol**: This feature shows a significant difference (p = 6.48e-14). Surprisingly, the mean `cholesterol` is slightly **lower** in the heart disease group (208.57 mg/dl) compared to the no disease group (233.15 mg/dl). This counterintuitive finding might warrant further investigation into medication effects or specific patient cohorts within the dataset.

- **Resting BP (systolic)**: There is a significant difference in `resting bp s` (p = 8.73e-04). The mean `resting bp s` is slightly **higher** in the heart disease group (133.00 mm Hg) than in the no disease group (130.56 mm Hg), which aligns with hypertension being a risk factor.

These findings suggest that `oldpeak`, `max heart rate`, `age`, and `resting bp s` are strong indicators for distinguishing between healthy individuals and those with heart disease, while `cholesterol` presents a more complex relationship.

# **8. Bivariate Analysis vs Target (Categorical)**

8.1 Disease rate within each category
"""

def category_disease_rate(df, col, target="target"):
    # Shows % of target=1 for each category
    rate = df.groupby(col)[target].mean().sort_values(ascending=False)
    counts = df[col].value_counts().sort_index()
    out = pd.DataFrame({"count": counts, "disease_rate": rate})
    return out.sort_values("disease_rate", ascending=False)

for col in cat_cols:
    print(f"\nDisease rate by category: {col}")
    display(category_disease_rate(df, col))

"""8.2 Chi-square association test (categorical vs target)"""

chi_rows = []
for col in cat_cols:
    table = pd.crosstab(df[col], df["target"])
    chi2, p, dof, expected = stats.chi2_contingency(table)
    chi_rows.append({"feature": col, "chi2": chi2, "p_value": p, "dof": dof})

chi_df = pd.DataFrame(chi_rows).sort_values("p_value")
display(chi_df)

"""### Summary of Categorical Bivariate Analysis

The categorical bivariate analysis, using disease rates by category and chi-square tests, reveals strong associations between several categorical features and the presence of heart disease. The chi-square test was employed to assess these associations, with low p-values indicating a significant relationship.

Looking at `chi_df`, the features with the most significant associations (lowest p-values) are:

- **Chest Pain Type (`chest pain type`)**: This feature shows the strongest association with heart disease. Specifically, `chest pain type` 4 (asymptomatic) has a very high heart disease rate, indicating that patients with no chest pain symptoms are frequently diagnosed with heart disease. Conversely, `chest pain type` 1 (typical angina) and `chest pain type` 2 (atypical angina) have lower disease rates. This highlights the importance of considering 'silent' symptoms.
- **ST Slope (`ST slope`)**: The slope of the peak exercise ST segment is also highly associated with heart disease. Categories 0, 1 and 2, which typically correspond to upsloping, flat or downsloping ST segments respectively, show varying disease rates. For instance, flat (value 2) and downsloping (value 0) ST segments are often indicative of higher disease prevalence compared to upsloping (value 1), suggesting significant diagnostic value.
- **Exercise Angina (`exercise angina`)**: The presence of exercise-induced angina (`exercise angina` = 1) is strongly linked to heart disease, with a significantly higher disease rate compared to those without exercise angina (`exercise angina` = 0). This aligns with clinical understanding of heart disease symptoms.

Other categorical features like `sex`, `fasting blood sugar`, and `resting ecg` also show statistically significant associations, though generally weaker than the top three. For example, males (`sex`=1) generally show a higher prevalence of heart disease than females (`sex`=0) in this dataset. Individuals with `fasting blood sugar` > 120 mg/dl (`fasting blood sugar` = 1) also tend to have a higher disease rate.

These findings underscore that various categorical clinical indicators are not merely descriptive but are significantly associated with heart disease status, offering valuable insights for risk assessment and diagnostic models.

# **9. Correlation & Relationships**

9.1 Correlation with target (numeric-only)
"""

# Correlation matrix for numeric columns + target
corr_cols = num_cols + ["target"]
corr = df[corr_cols].corr()

display(corr)

# Optional: visualize correlation matrix
plt.figure()
plt.imshow(corr, aspect="auto")
plt.xticks(range(len(corr_cols)), corr_cols, rotation=45, ha="right")
plt.yticks(range(len(corr_cols)), corr_cols)
plt.title("Correlation Matrix (Numeric + Target)")
plt.colorbar()
plt.tight_layout()
plt.show()

"""9.2 Simple “effect size” helper (difference in means)"""

def cohens_d(a, b):
    # Cohen’s d for two samples
    a = np.asarray(a); b = np.asarray(b)
    n1, n2 = len(a), len(b)
    s1, s2 = a.var(ddof=1), b.var(ddof=1)
    pooled = ((n1-1)*s1 + (n2-1)*s2) / (n1 + n2 - 2)
    return (a.mean() - b.mean()) / np.sqrt(pooled)

effect_rows = []
for col in num_cols:
    a = df[df["target"] == 0][col]
    b = df[df["target"] == 1][col]
    effect_rows.append({"feature": col, "cohens_d": cohens_d(a, b)})

effect_df = pd.DataFrame(effect_rows).sort_values("cohens_d")
display(effect_df)

"""### **Conclusion for Correlation and Relationships**

Based on the analysis of the correlation matrix and Cohen's d effect size, several numeric features stand out as influential indicators for heart disease.

**Correlation with Target:**

The correlation matrix (`corr['target'].drop('target')`) reveals the linear relationship between numeric features and the presence of heart disease. Features like `oldpeak` (ST depression) show a notable positive correlation, suggesting that higher values are associated with an increased likelihood of heart disease. Conversely, `max heart rate` tends to have a negative correlation, implying that lower maximum heart rates might be linked to heart disease. `Age` and `resting bp s` also show positive correlations, albeit weaker than `oldpeak`.

**Cohen's d Effect Size:**

Cohen's d measures the standardized difference between the means of two groups (here, healthy vs. diseased individuals). A larger absolute Cohen's d value indicates a stronger effect, meaning a greater difference in that feature between the two groups. The `effect_df` clearly shows that `oldpeak`, `max heart rate`, and `age` have the largest absolute Cohen's d values. This signifies substantial differences in these features between patients with and without heart disease. For instance, `oldpeak` tends to be significantly higher in the diseased group, while `max heart rate` tends to be significantly lower.

**Most Influential Numeric Features:**

Combining both analyses, `oldpeak` and `max heart rate` emerge as the most influential numeric features for heart disease prediction. `Oldpeak` consistently shows a strong positive correlation and a large Cohen's d, indicating that greater ST depression is a significant predictor of heart disease. `Max heart rate` exhibits a strong negative correlation and a large Cohen's d, suggesting that lower maximum heart rates achieved during exercise are highly associated with heart disease. `Age` also plays a significant role, showing a moderate positive correlation and a substantial Cohen's d, meaning older individuals are more prone to heart disease. While `cholesterol` and `resting bp s` show some correlation and effect size, their influence appears less pronounced compared to the exercise-related metrics and age.

# **10. Findings Summary Generator**
"""

# Identify top signals from:
# - t-test (numeric) and chi-square (categorical)
top_numeric = ttest_df.head(5)[["feature", "mean_target0", "mean_target1", "p_value"]]
top_categorical = chi_df.head(5)[["feature", "chi2", "p_value"]]

print("Top numeric differences (by p-value):")
display(top_numeric)

print("Top categorical associations (by chi-square p-value):")
display(top_categorical)

# Simple narrative lines for numeric
for _, r in top_numeric.iterrows():
    direction = "higher" if r["mean_target1"] > r["mean_target0"] else "lower"
    print(f"- {r['feature']}: mean is {direction} in disease group (p={r['p_value']:.2e}).")

"""## Summary:

### Data Analysis Key Findings

*   **Numeric Bivariate Analysis**:
    *   **Oldpeak**: Individuals with heart disease (`target=1`) have a significantly higher mean `oldpeak` (1.57) compared to those without (0.42), with a highly significant p-value (1.90e-40).
    *   **Max Heart Rate**: The mean `max heart rate` is significantly lower in the heart disease group (130.68) than in the no disease group (160.01), with a strong significant p-value (1.43e-36).
    *   **Age**: The heart disease group has a significantly higher mean `age` (57.19 years) compared to the no disease group (51.68 years), with a significant p-value (6.35e-18).
    *   **Cholesterol**: The mean `cholesterol` is slightly lower in the heart disease group (208.57 mg/dl) compared to the no disease group (233.15 mg/dl), with a significant p-value (6.48e-14).
    *   **Resting BP (systolic)**: The mean `resting bp s` is slightly higher in the heart disease group (133.00 mm Hg) than in the no disease group (130.56 mm Hg), with a significant p-value (8.73e-04).
*   **Categorical Bivariate Analysis**:
    *   **Chest Pain Type**: Shows the strongest association with heart disease; `chest pain type` 4 (asymptomatic) has a very high heart disease rate.
    *   **ST Slope**: Highly associated; flat (value 2) and downsloping (value 0) ST segments are indicative of higher disease prevalence.
    *   **Exercise Angina**: The presence of exercise-induced angina (`exercise angina` = 1) is strongly linked to a significantly higher disease rate.
    *   Other features like `sex` (males show higher prevalence) and `fasting blood sugar` (FBS > 120 mg/dl shows higher disease rate) also show significant associations.
*   **Correlation and Relationships**:
    *   **Most Influential Numeric Features**: `oldpeak` and `max heart rate` emerge as the most influential features, showing strong correlations with the target variable and large Cohen's d effect sizes.
    *   `Oldpeak` exhibits a strong positive correlation, and `max heart rate` shows a strong negative correlation with heart disease.
    *   `Age` also plays a significant role, showing a moderate positive correlation and a substantial Cohen's d.

# 11. Graphics for the website

**11.1 Disease Rate by Risk Factor (Bar Chart)**

📊 Chart description

Bar chart showing the proportion of patients with heart disease for each chest pain category.

📝 Interpretation & Insight

This visualization highlights a strong relationship between chest pain type and the presence of heart disease.

Patients classified as having asymptomatic chest pain exhibit the highest prevalence of heart disease, indicating that the absence of pain does not imply low cardiovascular risk.

In contrast, individuals with non-anginal or atypical chest pain demonstrate substantially lower disease rates.

These findings emphasize the diagnostic importance of chest pain classification and support clinical evidence that silent or atypical symptoms are common among high-risk cardiovascular patients.
"""

# Disease rate by categorical feature (example: chest pain type)
feature = "chest pain type"

rates = df.groupby(feature)["target"].mean().sort_values()

plt.figure()
rates.plot(kind="bar")
plt.ylabel("Heart Disease Rate")
plt.xlabel(feature)
plt.title("Heart Disease Rate by Chest Pain Type")
plt.ylim(0, 1)
plt.show()

"""**11.2. Distribution Comparison (Healthy vs Diseased)**

📊 Chart description

Overlapping histograms comparing ST depression values between healthy individuals and patients with heart disease.

📝 Interpretation & Insight

This distribution comparison reveals a clear separation between healthy individuals and patients with heart disease in terms of ST segment depression during exercise.

Patients diagnosed with heart disease tend to exhibit higher oldpeak values, reflecting abnormal cardiac response to physical stress.

This pattern reinforces the clinical relevance of exercise-induced ST changes as a key indicator of myocardial ischemia and cardiovascular dysfunction.
"""

feature = "oldpeak"

plt.figure()
df[df["target"] == 0][feature].hist(alpha=0.6, bins=30, label="No Disease")
df[df["target"] == 1][feature].hist(alpha=0.6, bins=30, label="Heart Disease")
plt.legend()
plt.xlabel(feature)
plt.ylabel("Count")
plt.title("ST Depression Distribution by Heart Disease Status")
plt.show()

"""**11.3. Effect Size Ranking**

Which features matter most?

📊 Chart description

Horizontal bar chart ranking clinical features by Cohen’s d effect size.

📝 Interpretation & Insight

This visualization ranks clinical variables according to their effect size, providing a direct measure of how strongly each feature differentiates between healthy individuals and patients with heart disease.

Exercise-related features, including ST depression, maximum heart rate achieved, and exercise-induced angina, demonstrate the largest effect sizes, indicating substantial differences between groups.

Traditional laboratory measurements, such as cholesterol, show comparatively smaller effect sizes, suggesting a more limited discriminative role when considered independently.

These results highlight the superior diagnostic value of functional cardiovascular stress indicators.
"""

# Effect size bar chart
plt.figure()
effect_df.sort_values("cohens_d").plot(
    x="feature",
    y="cohens_d",
    kind="barh",
    legend=False
)
plt.axvline(0, linestyle="--")
plt.xlabel("Cohen's d (Effect Size)")
plt.title("Effect Size of Features on Heart Disease Presence")
plt.show()

"""**11.4. Correlation with Target (Clean, Focused)**

📊 Chart description

Bar chart illustrating the correlation between numeric clinical features and heart disease status.

📝 Interpretation & Insight

This chart summarizes the linear relationships between key clinical variables and heart disease presence.

Variables related to cardiac stress response, such as maximum heart rate and ST depression, exhibit stronger correlations with heart disease compared to static risk factors.

Although correlation does not imply causation, these associations provide valuable insights into which physiological measurements are most consistently linked to cardiovascular pathology within the dataset.
"""

corr_with_target = corr["target"].drop("target").sort_values()

plt.figure()
corr_with_target.plot(kind="barh")
plt.xlabel("Correlation with Heart Disease")
plt.title("Feature Correlation with Heart Disease")
plt.show()