export enum Keys {
  PORT = "PORT",
  NODE_ENV = "NODE_ENV",
  API_URL = "API_URL",
  CLIENT_URL = "CLIENT_URL",
  CORS_ORIGIN = "CORS_ORIGIN",
  LOG_LEVEL = "LOG_LEVEL",
  SENTRY_DSN = "SENTRY_DSN",
  REDIS_HOST = "REDIS_HOST",
}
